###Listar todos os alugueis
GET http://localhost:3001/bike
Content-Type: application/json

###Listar alugueis pelo id
GET http://localhost:3001/bike/1
Content-Type: application/json

###Registrar aluguel
POST http://localhost:3001/bike
Content-Type: application/json

{
    "nome": "Cleiton",
    "data_inicio": "2025-12-04 20:00:00",
    "data_termino": "2025-12-04 20:00:00",
    "valor": 70,
    "status": "Ativo"
}

###Atualizar aluguel
PUT http://localhost:3001/bike/3
Content-Type: application/json

{
    "novoStatus": "Atrasado",
    "novaData_termino": "2025-03-13 21:00:00"
}

###Deleta Aluguel
DELETE http://localhost:3001/bike/1